<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
 <title>SIDN Labs Workbench</title>
 <meta charset="utf-8" />
 <meta name="description"    content="" />
 <meta name="keywords"       content="" />
 <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
 <link type="text/css" rel="stylesheet" href="/assets/css/layout.css" />

 <meta name="msapplication-square70x70logo"   content="/assets/img/favicons/windows-tile-70x70.png" />
 <meta name="msapplication-square150x150logo" content="/assets/img/favicons/windows-tile-150x150.png" />
 <meta name="msapplication-square310x310logo" content="/assets/img/favicons/windows-tile-310x310.png" />
 <meta name="msapplication-TileImage"         content="/assets/img/favicons/windows-tile-144x144.png" />
 <meta name="msapplication-TileColor"         content="#CEE7F3" />

 <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/assets/img/favicons/apple-touch-icon-152x152-precomposed.png" />
 <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/assets/img/favicons/apple-touch-icon-120x120-precomposed.png" />
 <link rel="apple-touch-icon-precomposed" sizes="76x76"   href="/assets/img/favicons/apple-touch-icon-76x76-precomposed.png" />
 <link rel="apple-touch-icon-precomposed" sizes="60x60"   href="/assets/img/favicons/apple-touch-icon-60x60-precomposed.png" />
 <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/img/favicons/apple-touch-icon-144x144-precomposed.png" />
 <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/img/favicons/apple-touch-icon-114x114-precomposed.png" />
 <link rel="apple-touch-icon-precomposed" sizes="72x72"   href="/assets/img/favicons/apple-touch-icon-72x72-precomposed.png" />
 <link rel="apple-touch-icon"             sizes="57x57"   href="/assets/img/favicons/apple-touch-icon.png" />

 <link rel="icon"                         sizes="228x228" href="/assets/img/favicons/coast-icon-228x228.png" />
 <link rel="shortcut icon"                                href="/assets/img/favicons/favicon.ico" />
 <link rel="icon" type="image/png"        sizes="64x64"   href="/assets/img/favicons/favicon.png" />
</head>

<body>
    <nav class="pushy pushy-right"></nav>
    <div class="site__overlay"></div>
    <div class="site theme--undefined">
        <div class="site__header">
        
         <div class="container">
      
<div class="site__navigation">

    <div class="logo logo--sidnlabs">
        <a class="logo__link logo__link--sidnlabs" href="/">
            <svg class="icon logo__icon logo__icon--sidnlabs">
                <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/assets/img/icons.svg#icon--sidnlabs-logo--fc">
                </use>
            </svg>
        </a>
    </div>

    <div class="site__navigation-container">

        <div class="nav nav--primary">
            <nav role="nav">
                <ul class="nav__list nav__list--primary">
                                            <li class="nav__list-item nav__list-item--primary " >
                                                            <a class="nav__link nav__link--primary" href="https://www.sidnlabs.nl">SIDN Labs</a>
                                            </li>
                                            <li class="nav__list-item nav__list-item--primary " >
                                                            <a class="nav__link nav__link--primary" href="//sidn.nl/t/over-sidn">Over SIDN</a>
                                            </li>
                </ul>
            </nav>
        </div>

        <div class="nav nav--secondary">
            <nav role="nav">
                <ul class="nav__list nav__list--secondary">
                    <li class="nav__list-item nav__list-item--secondary"></li>
                </ul>
            </nav>
        </div>

    </div>

    <div class="nav nav--trigger">
        <nav>
            <ul class="nav__list nav__list--trigger">
                <li class="nav__list-item nav__list-item--trigger">
                    <a class="nav__link nav__link--trigger" href="//sidn.nl/whois" data-search-toggle="domains" data-target="domains">
                         <svg class="icon">
    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/assets/img/icons.svg#icon--whois"></use>
</svg>
                        <span class="nav__title nav__title--trigger">form.label.whois</span>
                    </a>
                </li>
                <li class="nav__list-item nav__list-item--trigger">
                    <a class="nav__link nav__link--trigger" href="//sidn.nl/zoeken/" data-search-toggle="site" data-target="site">
                         <svg class="icon">
    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/assets/img/icons.svg#icon--search"></use>
</svg>
                        <span class="nav__title nav__title--trigger">Zoeken</span>
                    </a>
                </li>
                <li class="nav__list-item nav__list-item--trigger">
                    <a class="nav__link nav__link--trigger" href="#" id="nav__trigger">
                         <svg class="icon">
    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/assets/img/icons.svg#icon--menu"></use>
</svg>
                        <span class="nav__title nav__title--trigger">Mobiele navigatie</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>


      
      
  
  </div>

      
      
  
                          <div class="search-bar">
                <div class="container">
                      
  
      
    
        
          <div class="search search--site" id="search--site">
    <form class="search__form search__form--site" action="/search" method="get">
        <fieldset>
            <legend class="search__legend">Zoek in sidn.nl</legend>
             <svg class="icon search__icon search__icon--search">
    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/assets/img/icons.svg#icon--search--simple"></use>
</svg>
            <input class="search__input search__input--site" type="search" placeholder="Zoek in sidn.nl" value="" name="q" />
            <button class="search__button search__button--site">
                 <svg class="icon search__icon search__icon--submit">
    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/assets/img/icons.svg#icon--ok"></use>
</svg>
                <span class="button__label">Zoek</span>
            </button>
        </fieldset>
    </form>
</div>

      
      
  
                        
  
      
    
        
          <div class="search search--domains" id="search--domains">
    <form class="search__form search__form--domains" method="get" action="/whois" id="search__form--domains">
        <fieldset>
            <legend class="search__legend">whois.label.legend</legend>
             <svg class="icon search__icon search__icon--domains">
    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/assets/img/icons.svg#icon--whois"></use>
</svg>
            <input class="search__input search__input--domains" autocomplete="off" type="search" placeholder="Check hier je .nl-domeinnaam" value="" name="q" required/>
            <button class="search__button search__button--domains">
                 <svg class="icon search__icon search__icon--submit">
    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/assets/img/icons.svg#icon--ok"></use>
</svg>
                <span class="button__label">ok</span>
            </button>
        </fieldset>
    </form>
</div>

      
      
  
                  </div>
            </div>
        </div>

        <div id="hook"></div>

    <div class="site__content">
      <div class="container container--content">
        <div class="columns">
          <div class="column column--main">                                                                                                                   		     	
		   
