wb.sidnlabs.nl.	60	IN	SOA	bind9.sidnlabs.nl. hostmaster.sidnlabs.nl. 0 3600 600 3600 3600
apexcname.wb.sidnlabs.nl.	60	IN	NS	powerdns.sidnlabs.nl.
types-signed.wb.sidnlabs.nl.	60	IN	NS	powerdns.sidnlabs.nl.
types-signed.wb.sidnlabs.nl.	60	IN	NS	bind9.sidnlabs.nl.
types-signed.wb.sidnlabs.nl.	60	IN	NS	nsd4.sidnlabs.nl.
types-signed.wb.sidnlabs.nl.	60	IN	NS	knot.sidnlabs.nl.
;types-signed.wb.sidnlabs.nl.	60	IN	NS	nsd.sidnlabs.nl.
types-signed.wb.sidnlabs.nl.	60	IN	NS	yadifa.sidnlabs.nl.
types.wb.sidnlabs.nl.	60	IN	NS	powerdns.sidnlabs.nl.
types.wb.sidnlabs.nl.	60	IN	NS	bind9.sidnlabs.nl.
types.wb.sidnlabs.nl.	60	IN	NS	nsd4.sidnlabs.nl.
types.wb.sidnlabs.nl.	60	IN	NS	knot.sidnlabs.nl.
;types.wb.sidnlabs.nl.	60	IN	NS	nsd.sidnlabs.nl.
types.wb.sidnlabs.nl.	60	IN	NS	yadifa.sidnlabs.nl.
bad-dnssec.wb.sidnlabs.nl.	60	IN	NS	powerdns.sidnlabs.nl.
bad-dnssec.wb.sidnlabs.nl.	60	IN	NS	bind9.sidnlabs.nl.
bad-dnssec.wb.sidnlabs.nl.	60	IN	NS	nsd4.sidnlabs.nl.
bad-dnssec.wb.sidnlabs.nl.	60	IN	NS	knot.sidnlabs.nl.
;bad-dnssec.wb.sidnlabs.nl.	60	IN	NS	nsd.sidnlabs.nl.
bad-dnssec.wb.sidnlabs.nl.	60	IN	NS	yadifa.sidnlabs.nl.
delegations.wb.sidnlabs.nl.   60      IN      NS      powerdns.sidnlabs.nl.
delegations.wb.sidnlabs.nl.   60      IN      NS      bind9.sidnlabs.nl.
delegations.wb.sidnlabs.nl.   60      IN      NS      nsd4.sidnlabs.nl.
delegations.wb.sidnlabs.nl.   60      IN      NS      knot.sidnlabs.nl.
;delegations.wb.sidnlabs.nl.   60      IN      NS      nsd.sidnlabs.nl.
delegations.wb.sidnlabs.nl.   60      IN      NS      yadifa.sidnlabs.nl.
wb.sidnlabs.nl.	60	IN	DNSKEY	257 3 8 AwEAAc1cmNHVLDEzIQNLgskgkzY0MYUKCq3h+2NBOToCLHiXIe1I91r/8H0RwUr/5mma4C13BnsY5c3U8eL2Z2CqwFH/B3D7/R4UqhUepU7nafcr0zfGTuUmx5Egcvht39zcqM8jHxdeyatBCUq8c7k3aOnXfANEgAJLCbSCDoy6ZUzWE4Y81bWHo6seCa+ciZ/hu7kuwDrNtdCJU+itFvMHx9xplHet/OlxyJB4K1cevXb2OXuRy+wsqX58u/KiGrY/ylQTYyzGQ1JINkj3eekyX4wOPiTRBmiiK9830YcZjQphRYTz7yhv3gzkp26SOgeo40xJuSGwn0eGZkM2nBRT2Bk= ;{id = 44704 (ksk), size = 2048b}
wb.sidnlabs.nl.	60	IN	DNSKEY	256 3 8 AwEAAegq4GK6fqxM8o78keKd+WvXhTNwrAMB26ifngEpJpdaBYkFDlOFxVr3ei7QaifPgObqc1wBhIzWPCe+c0ucP+pOGeR/NiUHGc7fAamjv5T0FtFlg0c9d9qjwq9mPI7H5zavTg2obaM4pyaAQFFEyhUuK1B85LiHdGozYCPAnrlSOGGN1dW664yaT9gebS6z69rFJSA16S9tndR+CXedC7XN+luKIm1cobn0S26OqRbeifxooHb7uU0NHnO/L5Dg28duevlTVDv6/fcv4igwBdCJcUYI8e5r7MtmSceWA6OLQqp35v0uoN6jTI9kLJBWVOMN+WZxafeIse29mWlavaM= ;{id = 48378 (zsk), size = 2048b}
wb.sidnlabs.nl.	60	IN	NS	powerdns.sidnlabs.nl.
wb.sidnlabs.nl.	60	IN	NS	bind9.sidnlabs.nl.
wb.sidnlabs.nl.	60	IN	NS	nsd4.sidnlabs.nl.
wb.sidnlabs.nl.	60	IN	NS	knot.sidnlabs.nl.
;wb.sidnlabs.nl.	60	IN	NS	nsd.sidnlabs.nl.
wb.sidnlabs.nl.	60	IN	NS	yadifa.sidnlabs.nl.
;wb.sidnlabs.nl.	60	IN	A	94.198.159.25
wb.sidnlabs.nl.	60	IN	A	94.198.159.39
wildcards.wb.sidnlabs.nl.	60	IN	NS	powerdns.sidnlabs.nl.
wildcards.wb.sidnlabs.nl.	60	IN	NS	bind9.sidnlabs.nl.
wildcards.wb.sidnlabs.nl.	60	IN	NS	nsd4.sidnlabs.nl.
wildcards.wb.sidnlabs.nl.	60	IN	NS	knot.sidnlabs.nl.
;wildcards.wb.sidnlabs.nl.	60	IN	NS	nsd.sidnlabs.nl.
wildcards.wb.sidnlabs.nl.	60	IN	NS	yadifa.sidnlabs.nl.
wildcards-nsec3.wb.sidnlabs.nl.	60	IN	NS	powerdns.sidnlabs.nl.
wildcards-nsec3.wb.sidnlabs.nl.	60	IN	NS	bind9.sidnlabs.nl.
wildcards-nsec3.wb.sidnlabs.nl.	60	IN	NS	nsd4.sidnlabs.nl.
wildcards-nsec3.wb.sidnlabs.nl.	60	IN	NS	knot.sidnlabs.nl.
;wildcards-nsec3.wb.sidnlabs.nl.	60	IN	NS	nsd.sidnlabs.nl.
wildcards-nsec3.wb.sidnlabs.nl.	60	IN	NS	yadifa.sidnlabs.nl.
